#!/usr/bin/env zsh

set -e

# via DHH
#   - https://x.com/dhh/status/1785016820740788495
#   - https://gist.github.com/dhh/c5051aae633ff91bc4ce30528e4f0b60
RED=31; GREEN=32; YELLOW=33; BLUE=34; MAGENTA=35; BOLD=1
announce() { echo -e "\033[0;${2}m${1}\033[0m"; }

install_and_update_asdf_plugin() {
  echo "installing $1 asdf plugin"
  asdf plugin-add "$1" || echo "asdf $1 plugin is already installed"
  asdf plugin-update "$1"
}

if [[ "$(uname)" == "Darwin" ]]; then
  if [[ $* == *--update* ]]
  then
    echo "running brew upgrade"
    brew upgrade
  fi
  brew bundle --file .bin/Brewfile
  brew cleanup
else
  echo "Unsupported system: $(uname)"
  exit 1
fi

# asdf managed from brew
# from https://asdf-vm.com/#/core-manage-asdf
# git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.8.1 || echo "asdf already installed"
# source ~/.asdf/asdf.sh
# asdf update

# for plugin in nodejs postgres python ruby rust yarn redis
# do
#   install_and_update_asdf_plugin $plugin
# done
# asdf install
mise install

# intall other command line tools like angular
command -v ng &> /dev/null || \
  npm install --global @angular/cli && \
  announce "✅ angular installed" $BLUE
